// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace mtcg.Migrations
{
    [DbContext(typeof(mtcgDbContext))]
    [Migration("20240127134728_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Battle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Player1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Player2Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("BattleResult", b =>
                {
                    b.Property<Guid>("BattleResultId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDraw")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("BattleResultId");

                    b.ToTable("BattleResults");
                });

            modelBuilder.Entity("Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Damage")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("NumberOfCards")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BattleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDraw")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("Player1CardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Player2CardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.HasIndex("Player1CardId");

                    b.HasIndex("Player2CardId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("TradingDeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardToTrade")
                        .HasColumnType("uuid");

                    b.Property<double>("MinimumDamage")
                        .HasColumnType("double precision");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TradingDeals");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("StatsUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StatsUserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("UserStats", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Elo")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("BattleResult", b =>
                {
                    b.HasOne("Battle", null)
                        .WithOne("Result")
                        .HasForeignKey("BattleResult", "BattleResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Card", b =>
                {
                    b.HasOne("Package", null)
                        .WithMany("Cards")
                        .HasForeignKey("PackageId");
                });

            modelBuilder.Entity("Round", b =>
                {
                    b.HasOne("Battle", null)
                        .WithMany("Rounds")
                        .HasForeignKey("BattleId");

                    b.HasOne("Card", "Player1Card")
                        .WithMany()
                        .HasForeignKey("Player1CardId");

                    b.HasOne("Card", "Player2Card")
                        .WithMany()
                        .HasForeignKey("Player2CardId");

                    b.Navigation("Player1Card");

                    b.Navigation("Player2Card");
                });

            modelBuilder.Entity("UserProfile", b =>
                {
                    b.HasOne("UserStats", "Stats")
                        .WithMany()
                        .HasForeignKey("StatsUserId");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("UserStats", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("UserStats")
                        .HasForeignKey("UserStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Battle", b =>
                {
                    b.Navigation("Result");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Package", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("UserStats");
                });
#pragma warning restore 612, 618
        }
    }
}
